name: Tauri 2 Multi-Platform Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact-name: windows
            output-path: src-tauri/target/x86_64-pc-windows-msvc/release/bundle/

          - os: macos-latest
            target: x86_64-apple-darwin
            artifact-name: macos-x86_64
            output-path: src-tauri/target/x86_64-apple-darwin/release/bundle/

          - os: macos-latest
            target: aarch64-apple-darwin
            artifact-name: macos-arm64
            output-path: src-tauri/target/aarch64-apple-darwin/release/bundle/

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact-name: linux-x86_64
            output-path: src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/
            dependencies: >
              libwebkit2gtk-4.1-dev build-essential curl wget file libssl-dev libgtk-3-dev
              libayatana-appindicator3-dev librsvg2-dev patchelf

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-latest' && matrix.dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.dependencies }}

      - name: Install npm dependencies (including Tauri CLI)
        run: npm install

      - name: Build Tauri app
        run: npx tauri build --target ${{ matrix.target }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build-${{ matrix.artifact-name }}
          path: ${{ matrix.output-path }}
          if-no-files-found: error
