name: Tauri 2 Android APK Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Set up Java (for Android SDK)
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          # 禁用 Gradle 缓存检查（解决文件匹配错误）
          cache: ""

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Initialize Tauri Android environment
        run: npm run tauri android init
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          # 确保 Tauri 能找到 Java 环境
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}

      - name: Build Tauri Android APK
        run: npm run tauri android build -- --target aarch64 --debug
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-android-apk
          path: |
            src-tauri/target/aarch64-linux-android/release/bundle/apk/*.apk
            src-tauri/target/armv7-linux-androideabi/release/bundle/apk/*.apk
            src-tauri/target/x86_64-linux-android/release/bundle/apk/*.apk
