name: Tauri 2 Multi-Platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # 单个平台失败不影响其他平台
      matrix:
        # 直接定义平台数组，每个元素包含完整配置
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact-name: windows
            build-command: cargo tauri build --target x86_64-pc-windows-msvc
            output-path: src-tauri/target/x86_64-pc-windows-msvc/release/bundle/

          - os: macos-latest
            target: x86_64-apple-darwin
            artifact-name: macos-x86_64
            build-command: cargo tauri build --target x86_64-apple-darwin
            output-path: src-tauri/target/x86_64-apple-darwin/release/bundle/

          - os: macos-latest
            target: aarch64-apple-darwin
            artifact-name: macos-arm64
            build-command: cargo tauri build --target aarch64-apple-darwin
            output-path: src-tauri/target/aarch64-apple-darwin/release/bundle/

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact-name: linux-x86_64
            build-command: cargo tauri build --target x86_64-unknown-linux-gnu
            output-path: src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/
            dependencies: >
              libwebkit2gtk-4.1-dev build-essential curl wget file libssl-dev libgtk-3-dev
              libayatana-appindicator3-dev librsvg2-dev patchelf

          - os: ubuntu-latest
            target: aarch64-linux-android
            artifact-name: android
            build-command: cargo tauri build --target aarch64-linux-android
            output-path: src-tauri/target/aarch64-linux-android/release/bundle/
            dependencies: >
              openjdk-17-jdk android-sdk-platform-tools android-sdk-build-tools
              libwebkit2gtk-4.1-dev build-essential

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-latest' && matrix.dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.dependencies }}

      - name: Setup Android SDK
        if: matrix.target == 'aarch64-linux-android'
        uses: android-actions/setup-android@v3

      - name: Install npm dependencies
        run: npm ci

      - name: Build Tauri app
        run: ${{ matrix.build-command }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build-${{ matrix.artifact-name }}
          path: ${{ matrix.output-path }}
          if-no-files-found: error
